### ISSUE TITLE
error: pickle file not found，how can i train CDL dataset by myself?  i don't want to use the  preprocessed data

### ISSUE THREAD

**Issue by Bchenyang** [Jinwon-Ko/SLCD#1]
If I want to retrain the CDL dataset myself without using your preprocessed data, can I do that? I tried training directly, but it reported an error saying it couldn't find the pickle file. Why is that?

(SLCD) baicy@cmcs232-System-Product-Name:~/SLCD/Modeling/SLCD/code$ python main.py 
------------ Options -------------
root: /home/baicy/SLCD/Modeling/SLCD
dataset_name: CDL
gpu: 1
model_name: combination_
viz: False
run_mode: train
save_pickle: False
dataset_root: /home/baicy/SLCD/Modeling/SLCD/../../Datasets/CDL/
image_size: 480
batch_size: 2
num_workers: 4
height: 480
width: 480
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
max_theta: 90
max_radius: 240
n_max: 8
backbone: resnet50
train_backbone: True
pretrained: True
dim_feedforward: 2048
hidden_dim: 96
query_dim: 2
nheads: 6
dropout: 0.0
gaussian_sigma: 20
n_enc_layers: 3
n_dec_layers: 3
set_cost_class: 0
set_cost_line: 1
focal_alpha: 0.25
epochs: 300
optim: {'weight_decay': 0.0001, 'gamma': 0.5, 'betas': (0.9, 0.999), 'eps': 1e-08, 'mode': 'adam_w'}
scheduler: MultiStepLR
backbone_lr: 0.0001
lr: 0.0001
weight_decay: 0
milestones: [30, 60, 90, 120, 150]
gamma: 0.5
aux_loss: True
interm_loss: False
interm_loss_coef: 0.5
loss_kld_coef: 0.05
loss_cls_coef: 1
loss_reg_coef: 5
threshold_theta: 2.5
threshold_radius: 4
start_eval_epoch: 1
prob_threshold: 0.5
test_nms_threshold: 0.01
use_semantic_feat: True
use_KLD: True
num_region_queries: 8
num_anchors: 1024
topk: 8
exp: MS_agg_mq8_nq1024_semantic_feat_w_KLD
code_name: code
output_name: output
proj_root: /home/baicy/SLCD/Modeling/SLCD/code
output_root: /home/baicy/SLCD/Modeling/SLCD/output/MS_agg_mq8_nq1024_semantic_feat_w_KLD
exp_name: combination_CDL
viz_dir: /home/baicy/SLCD/Modeling/SLCD/output/MS_agg_mq8_nq1024_semantic_feat_w_KLD/display/combination_CDL
save_folder: /home/baicy/SLCD/Modeling/SLCD/output/MS_agg_mq8_nq1024_semantic_feat_w_KLD/weights/combination_CDL
detector_ckpt: /home/baicy/SLCD/Modeling/SLCD/output/Detector_result/CDL/ckpt/checkpoint_best_recall.pth
init_model: /home/baicy/SLCD/Modeling/SLCD/output/MS_agg_mq8_nq1024_semantic_feat_w_KLD/weights/combination_CDL/ckpt/checkpoint_best_line_detection.pth
pickle_dir: /home/baicy/SLCD/Modeling/SLCD/output/Detector_result/CDL/forward_detector/pickle
-------------- End ----------------
/home/baicy/miniconda3/envs/SLCD/lib/python3.6/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1639180593867/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/baicy/SLCD/Modeling/SLCD/code/models/tools/network_tools.py:29: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  self.line_pts = line_pts / (self.size - 1) * (self.size // scale_factor - 1)
/home/baicy/miniconda3/envs/SLCD/lib/python3.6/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
/home/baicy/miniconda3/envs/SLCD/lib/python3.6/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
/home/baicy/miniconda3/envs/SLCD/lib/python3.6/site-packages/torchvision/transforms/transforms.py:288: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
Epoch 000 ========================================================
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    do_train_process(args, model, criterion, optimizer, lr_scheduler)
  File "/home/baicy/SLCD/Modeling/SLCD/code/engines/get_train_process.py", line 21, in do_train_process
    model, optimizer = train_line_detection_with_combination(cfg, epoch, model, train_loader, criterion, optimizer)
  File "/home/baicy/SLCD/Modeling/SLCD/code/engines/train/train_process.py", line 110, in train_line_detection_with_combination
    for i, batch in enumerate(train_loader):
  File "/home/baicy/miniconda3/envs/SLCD/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/baicy/miniconda3/envs/SLCD/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/baicy/miniconda3/envs/SLCD/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/baicy/miniconda3/envs/SLCD/lib/python3.6/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/baicy/miniconda3/envs/SLCD/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/baicy/miniconda3/envs/SLCD/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/baicy/miniconda3/envs/SLCD/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/baicy/SLCD/Modeling/SLCD/code/dataloaders/CDL/CDL_dataset.py", line 422, in __getitem__
    out = self.get_detector_results(img_name, flip)
  File "/home/baicy/SLCD/Modeling/SLCD/code/dataloaders/CDL/CDL_dataset.py", line 384, in get_detector_results
    with open(pickle_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/baicy/SLCD/Modeling/SLCD/output/Detector_result/CDL/forward_detector/pickle/HORIZONTAL_0177.pickle'

(SLCD) baicy@cmcs232-System-Product-Name:~/SLCD/Modeling/SLCD/code$

**Comment by Jinwon-Ko** [comment]
I modified the code (Modeling/SLCD/code/engines/get_train_process.py) to perform preprocessing when no preprocessed data is available.

Thanks.

**Comment by Bchenyang** [comment]
Thanks, I tried again, and it shows that checkpoint_best_recall.pth is not found. Do I need to first train the Detector, copy the resulting .pth file to the corresponding folder, and then train SLCD? 


Traceback (most recent call last):
  File "main.py", line 31, in <module>
    do_train_process(args, model, criterion, optimizer, lr_scheduler)
  File "/home/baicy/SLCD/Modeling/SLCD/code/engines/get_train_process.py", line 26, in do_train_process
    checkpoint = torch.load(cfg.detector_ckpt)
  File "/home/baicy/miniconda3/envs/SLCD/lib/python3.6/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/baicy/miniconda3/envs/SLCD/lib/python3.6/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/baicy/miniconda3/envs/SLCD/lib/python3.6/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/baicy/SLCD/Modeling/SLCD/output/Detector_result/CDL/ckpt/checkpoint_best_recall.pth'

**Comment by Bchenyang** [comment]
i'm training Detector now
